package com.pkh.pkec.phone.po;

import java.util.ArrayList;
import java.util.List;

public class CrmOptionItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public CrmOptionItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOptionIdIsNull() {
            addCriterion("option_id is null");
            return (Criteria) this;
        }

        public Criteria andOptionIdIsNotNull() {
            addCriterion("option_id is not null");
            return (Criteria) this;
        }

        public Criteria andOptionIdEqualTo(Integer value) {
            addCriterion("option_id =", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotEqualTo(Integer value) {
            addCriterion("option_id <>", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdGreaterThan(Integer value) {
            addCriterion("option_id >", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_id >=", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdLessThan(Integer value) {
            addCriterion("option_id <", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdLessThanOrEqualTo(Integer value) {
            addCriterion("option_id <=", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdIn(List<Integer> values) {
            addCriterion("option_id in", values, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotIn(List<Integer> values) {
            addCriterion("option_id not in", values, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdBetween(Integer value1, Integer value2) {
            addCriterion("option_id between", value1, value2, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("option_id not between", value1, value2, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdIsNull() {
            addCriterion("option_team_id is null");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdIsNotNull() {
            addCriterion("option_team_id is not null");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdEqualTo(Integer value) {
            addCriterion("option_team_id =", value, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdNotEqualTo(Integer value) {
            addCriterion("option_team_id <>", value, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdGreaterThan(Integer value) {
            addCriterion("option_team_id >", value, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_team_id >=", value, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdLessThan(Integer value) {
            addCriterion("option_team_id <", value, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdLessThanOrEqualTo(Integer value) {
            addCriterion("option_team_id <=", value, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdIn(List<Integer> values) {
            addCriterion("option_team_id in", values, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdNotIn(List<Integer> values) {
            addCriterion("option_team_id not in", values, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdBetween(Integer value1, Integer value2) {
            addCriterion("option_team_id between", value1, value2, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionTeamIdNotBetween(Integer value1, Integer value2) {
            addCriterion("option_team_id not between", value1, value2, "optionTeamId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdIsNull() {
            addCriterion("option_group_id is null");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdIsNotNull() {
            addCriterion("option_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdEqualTo(String value) {
            addCriterion("option_group_id =", value, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdNotEqualTo(String value) {
            addCriterion("option_group_id <>", value, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdGreaterThan(String value) {
            addCriterion("option_group_id >", value, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("option_group_id >=", value, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdLessThan(String value) {
            addCriterion("option_group_id <", value, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdLessThanOrEqualTo(String value) {
            addCriterion("option_group_id <=", value, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdLike(String value) {
            addCriterion("option_group_id like", value, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdNotLike(String value) {
            addCriterion("option_group_id not like", value, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdIn(List<String> values) {
            addCriterion("option_group_id in", values, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdNotIn(List<String> values) {
            addCriterion("option_group_id not in", values, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdBetween(String value1, String value2) {
            addCriterion("option_group_id between", value1, value2, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionGroupIdNotBetween(String value1, String value2) {
            addCriterion("option_group_id not between", value1, value2, "optionGroupId");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeIsNull() {
            addCriterion("option_item_code is null");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeIsNotNull() {
            addCriterion("option_item_code is not null");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeEqualTo(String value) {
            addCriterion("option_item_code =", value, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeNotEqualTo(String value) {
            addCriterion("option_item_code <>", value, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeGreaterThan(String value) {
            addCriterion("option_item_code >", value, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("option_item_code >=", value, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeLessThan(String value) {
            addCriterion("option_item_code <", value, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeLessThanOrEqualTo(String value) {
            addCriterion("option_item_code <=", value, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeLike(String value) {
            addCriterion("option_item_code like", value, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeNotLike(String value) {
            addCriterion("option_item_code not like", value, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeIn(List<String> values) {
            addCriterion("option_item_code in", values, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeNotIn(List<String> values) {
            addCriterion("option_item_code not in", values, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeBetween(String value1, String value2) {
            addCriterion("option_item_code between", value1, value2, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemCodeNotBetween(String value1, String value2) {
            addCriterion("option_item_code not between", value1, value2, "optionItemCode");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueIsNull() {
            addCriterion("option_item_value is null");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueIsNotNull() {
            addCriterion("option_item_value is not null");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueEqualTo(String value) {
            addCriterion("option_item_value =", value, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueNotEqualTo(String value) {
            addCriterion("option_item_value <>", value, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueGreaterThan(String value) {
            addCriterion("option_item_value >", value, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueGreaterThanOrEqualTo(String value) {
            addCriterion("option_item_value >=", value, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueLessThan(String value) {
            addCriterion("option_item_value <", value, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueLessThanOrEqualTo(String value) {
            addCriterion("option_item_value <=", value, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueLike(String value) {
            addCriterion("option_item_value like", value, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueNotLike(String value) {
            addCriterion("option_item_value not like", value, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueIn(List<String> values) {
            addCriterion("option_item_value in", values, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueNotIn(List<String> values) {
            addCriterion("option_item_value not in", values, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueBetween(String value1, String value2) {
            addCriterion("option_item_value between", value1, value2, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemValueNotBetween(String value1, String value2) {
            addCriterion("option_item_value not between", value1, value2, "optionItemValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueIsNull() {
            addCriterion("option_display_value is null");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueIsNotNull() {
            addCriterion("option_display_value is not null");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueEqualTo(String value) {
            addCriterion("option_display_value =", value, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueNotEqualTo(String value) {
            addCriterion("option_display_value <>", value, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueGreaterThan(String value) {
            addCriterion("option_display_value >", value, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueGreaterThanOrEqualTo(String value) {
            addCriterion("option_display_value >=", value, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueLessThan(String value) {
            addCriterion("option_display_value <", value, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueLessThanOrEqualTo(String value) {
            addCriterion("option_display_value <=", value, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueLike(String value) {
            addCriterion("option_display_value like", value, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueNotLike(String value) {
            addCriterion("option_display_value not like", value, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueIn(List<String> values) {
            addCriterion("option_display_value in", values, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueNotIn(List<String> values) {
            addCriterion("option_display_value not in", values, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueBetween(String value1, String value2) {
            addCriterion("option_display_value between", value1, value2, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionDisplayValueNotBetween(String value1, String value2) {
            addCriterion("option_display_value not between", value1, value2, "optionDisplayValue");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionIsNull() {
            addCriterion("option_item_discription is null");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionIsNotNull() {
            addCriterion("option_item_discription is not null");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionEqualTo(String value) {
            addCriterion("option_item_discription =", value, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionNotEqualTo(String value) {
            addCriterion("option_item_discription <>", value, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionGreaterThan(String value) {
            addCriterion("option_item_discription >", value, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionGreaterThanOrEqualTo(String value) {
            addCriterion("option_item_discription >=", value, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionLessThan(String value) {
            addCriterion("option_item_discription <", value, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionLessThanOrEqualTo(String value) {
            addCriterion("option_item_discription <=", value, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionLike(String value) {
            addCriterion("option_item_discription like", value, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionNotLike(String value) {
            addCriterion("option_item_discription not like", value, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionIn(List<String> values) {
            addCriterion("option_item_discription in", values, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionNotIn(List<String> values) {
            addCriterion("option_item_discription not in", values, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionBetween(String value1, String value2) {
            addCriterion("option_item_discription between", value1, value2, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionItemDiscriptionNotBetween(String value1, String value2) {
            addCriterion("option_item_discription not between", value1, value2, "optionItemDiscription");
            return (Criteria) this;
        }

        public Criteria andOptionOrderIsNull() {
            addCriterion("option_order is null");
            return (Criteria) this;
        }

        public Criteria andOptionOrderIsNotNull() {
            addCriterion("option_order is not null");
            return (Criteria) this;
        }

        public Criteria andOptionOrderEqualTo(Integer value) {
            addCriterion("option_order =", value, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderNotEqualTo(Integer value) {
            addCriterion("option_order <>", value, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderGreaterThan(Integer value) {
            addCriterion("option_order >", value, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_order >=", value, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderLessThan(Integer value) {
            addCriterion("option_order <", value, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderLessThanOrEqualTo(Integer value) {
            addCriterion("option_order <=", value, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderIn(List<Integer> values) {
            addCriterion("option_order in", values, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderNotIn(List<Integer> values) {
            addCriterion("option_order not in", values, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderBetween(Integer value1, Integer value2) {
            addCriterion("option_order between", value1, value2, "optionOrder");
            return (Criteria) this;
        }

        public Criteria andOptionOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("option_order not between", value1, value2, "optionOrder");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crm_option_item
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}