package com.pkh.pkec.phone.po;

public class CrmOptionItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_option_item.option_id
     *
     * @mbggenerated
     */
    private Integer optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_option_item.option_team_id
     *
     * @mbggenerated
     */
    private Integer optionTeamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_option_item.option_group_id
     *
     * @mbggenerated
     */
    private String optionGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_option_item.option_item_code
     *
     * @mbggenerated
     */
    private String optionItemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_option_item.option_item_value
     *
     * @mbggenerated
     */
    private String optionItemValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_option_item.option_display_value
     *
     * @mbggenerated
     */
    private String optionDisplayValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_option_item.option_item_discription
     *
     * @mbggenerated
     */
    private String optionItemDiscription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_option_item.option_order
     *
     * @mbggenerated
     */
    private Integer optionOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_option_item.option_id
     *
     * @return the value of crm_option_item.option_id
     *
     * @mbggenerated
     */
    public Integer getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_option_item.option_id
     *
     * @param optionId the value for crm_option_item.option_id
     *
     * @mbggenerated
     */
    public void setOptionId(Integer optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_option_item.option_team_id
     *
     * @return the value of crm_option_item.option_team_id
     *
     * @mbggenerated
     */
    public Integer getOptionTeamId() {
        return optionTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_option_item.option_team_id
     *
     * @param optionTeamId the value for crm_option_item.option_team_id
     *
     * @mbggenerated
     */
    public void setOptionTeamId(Integer optionTeamId) {
        this.optionTeamId = optionTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_option_item.option_group_id
     *
     * @return the value of crm_option_item.option_group_id
     *
     * @mbggenerated
     */
    public String getOptionGroupId() {
        return optionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_option_item.option_group_id
     *
     * @param optionGroupId the value for crm_option_item.option_group_id
     *
     * @mbggenerated
     */
    public void setOptionGroupId(String optionGroupId) {
        this.optionGroupId = optionGroupId == null ? null : optionGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_option_item.option_item_code
     *
     * @return the value of crm_option_item.option_item_code
     *
     * @mbggenerated
     */
    public String getOptionItemCode() {
        return optionItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_option_item.option_item_code
     *
     * @param optionItemCode the value for crm_option_item.option_item_code
     *
     * @mbggenerated
     */
    public void setOptionItemCode(String optionItemCode) {
        this.optionItemCode = optionItemCode == null ? null : optionItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_option_item.option_item_value
     *
     * @return the value of crm_option_item.option_item_value
     *
     * @mbggenerated
     */
    public String getOptionItemValue() {
        return optionItemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_option_item.option_item_value
     *
     * @param optionItemValue the value for crm_option_item.option_item_value
     *
     * @mbggenerated
     */
    public void setOptionItemValue(String optionItemValue) {
        this.optionItemValue = optionItemValue == null ? null : optionItemValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_option_item.option_display_value
     *
     * @return the value of crm_option_item.option_display_value
     *
     * @mbggenerated
     */
    public String getOptionDisplayValue() {
        return optionDisplayValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_option_item.option_display_value
     *
     * @param optionDisplayValue the value for crm_option_item.option_display_value
     *
     * @mbggenerated
     */
    public void setOptionDisplayValue(String optionDisplayValue) {
        this.optionDisplayValue = optionDisplayValue == null ? null : optionDisplayValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_option_item.option_item_discription
     *
     * @return the value of crm_option_item.option_item_discription
     *
     * @mbggenerated
     */
    public String getOptionItemDiscription() {
        return optionItemDiscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_option_item.option_item_discription
     *
     * @param optionItemDiscription the value for crm_option_item.option_item_discription
     *
     * @mbggenerated
     */
    public void setOptionItemDiscription(String optionItemDiscription) {
        this.optionItemDiscription = optionItemDiscription == null ? null : optionItemDiscription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_option_item.option_order
     *
     * @return the value of crm_option_item.option_order
     *
     * @mbggenerated
     */
    public Integer getOptionOrder() {
        return optionOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_option_item.option_order
     *
     * @param optionOrder the value for crm_option_item.option_order
     *
     * @mbggenerated
     */
    public void setOptionOrder(Integer optionOrder) {
        this.optionOrder = optionOrder;
    }
}