package com.pkh.pkec.phone.po;

import java.util.Date;

public class CustomerManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_code
     *
     * @mbggenerated
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_phone
     *
     * @mbggenerated
     */
    private String customerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_type
     *
     * @mbggenerated
     */
    private String customerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_company
     *
     * @mbggenerated
     */
    private String customerCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_sex
     *
     * @mbggenerated
     */
    private String customerSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.bind_card
     *
     * @mbggenerated
     */
    private String bindCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.weixin
     *
     * @mbggenerated
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_email
     *
     * @mbggenerated
     */
    private String customerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_address
     *
     * @mbggenerated
     */
    private String customerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_status
     *
     * @mbggenerated
     */
    private String customerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_delete
     *
     * @mbggenerated
     */
    private String customerDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_rank
     *
     * @mbggenerated
     */
    private String customerRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_handler
     *
     * @mbggenerated
     */
    private String customerHandler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_manage.customer_remark
     *
     * @mbggenerated
     */
    private String customerRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.id
     *
     * @return the value of crm_customer_manage.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.id
     *
     * @param id the value for crm_customer_manage.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_code
     *
     * @return the value of crm_customer_manage.customer_code
     *
     * @mbggenerated
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_code
     *
     * @param customerCode the value for crm_customer_manage.customer_code
     *
     * @mbggenerated
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_name
     *
     * @return the value of crm_customer_manage.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_name
     *
     * @param customerName the value for crm_customer_manage.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_phone
     *
     * @return the value of crm_customer_manage.customer_phone
     *
     * @mbggenerated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_phone
     *
     * @param customerPhone the value for crm_customer_manage.customer_phone
     *
     * @mbggenerated
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_type
     *
     * @return the value of crm_customer_manage.customer_type
     *
     * @mbggenerated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_type
     *
     * @param customerType the value for crm_customer_manage.customer_type
     *
     * @mbggenerated
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_company
     *
     * @return the value of crm_customer_manage.customer_company
     *
     * @mbggenerated
     */
    public String getCustomerCompany() {
        return customerCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_company
     *
     * @param customerCompany the value for crm_customer_manage.customer_company
     *
     * @mbggenerated
     */
    public void setCustomerCompany(String customerCompany) {
        this.customerCompany = customerCompany == null ? null : customerCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_sex
     *
     * @return the value of crm_customer_manage.customer_sex
     *
     * @mbggenerated
     */
    public String getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_sex
     *
     * @param customerSex the value for crm_customer_manage.customer_sex
     *
     * @mbggenerated
     */
    public void setCustomerSex(String customerSex) {
        this.customerSex = customerSex == null ? null : customerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.bind_card
     *
     * @return the value of crm_customer_manage.bind_card
     *
     * @mbggenerated
     */
    public String getBindCard() {
        return bindCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.bind_card
     *
     * @param bindCard the value for crm_customer_manage.bind_card
     *
     * @mbggenerated
     */
    public void setBindCard(String bindCard) {
        this.bindCard = bindCard == null ? null : bindCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.weixin
     *
     * @return the value of crm_customer_manage.weixin
     *
     * @mbggenerated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.weixin
     *
     * @param weixin the value for crm_customer_manage.weixin
     *
     * @mbggenerated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_email
     *
     * @return the value of crm_customer_manage.customer_email
     *
     * @mbggenerated
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_email
     *
     * @param customerEmail the value for crm_customer_manage.customer_email
     *
     * @mbggenerated
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail == null ? null : customerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_address
     *
     * @return the value of crm_customer_manage.customer_address
     *
     * @mbggenerated
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_address
     *
     * @param customerAddress the value for crm_customer_manage.customer_address
     *
     * @mbggenerated
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.create_user
     *
     * @return the value of crm_customer_manage.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.create_user
     *
     * @param createUser the value for crm_customer_manage.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.create_time
     *
     * @return the value of crm_customer_manage.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.create_time
     *
     * @param createTime the value for crm_customer_manage.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.update_time
     *
     * @return the value of crm_customer_manage.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.update_time
     *
     * @param updateTime the value for crm_customer_manage.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_status
     *
     * @return the value of crm_customer_manage.customer_status
     *
     * @mbggenerated
     */
    public String getCustomerStatus() {
        return customerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_status
     *
     * @param customerStatus the value for crm_customer_manage.customer_status
     *
     * @mbggenerated
     */
    public void setCustomerStatus(String customerStatus) {
        this.customerStatus = customerStatus == null ? null : customerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_delete
     *
     * @return the value of crm_customer_manage.customer_delete
     *
     * @mbggenerated
     */
    public String getCustomerDelete() {
        return customerDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_delete
     *
     * @param customerDelete the value for crm_customer_manage.customer_delete
     *
     * @mbggenerated
     */
    public void setCustomerDelete(String customerDelete) {
        this.customerDelete = customerDelete == null ? null : customerDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_rank
     *
     * @return the value of crm_customer_manage.customer_rank
     *
     * @mbggenerated
     */
    public String getCustomerRank() {
        return customerRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_rank
     *
     * @param customerRank the value for crm_customer_manage.customer_rank
     *
     * @mbggenerated
     */
    public void setCustomerRank(String customerRank) {
        this.customerRank = customerRank == null ? null : customerRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_handler
     *
     * @return the value of crm_customer_manage.customer_handler
     *
     * @mbggenerated
     */
    public String getCustomerHandler() {
        return customerHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_handler
     *
     * @param customerHandler the value for crm_customer_manage.customer_handler
     *
     * @mbggenerated
     */
    public void setCustomerHandler(String customerHandler) {
        this.customerHandler = customerHandler == null ? null : customerHandler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_manage.customer_remark
     *
     * @return the value of crm_customer_manage.customer_remark
     *
     * @mbggenerated
     */
    public String getCustomerRemark() {
        return customerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_manage.customer_remark
     *
     * @param customerRemark the value for crm_customer_manage.customer_remark
     *
     * @mbggenerated
     */
    public void setCustomerRemark(String customerRemark) {
        this.customerRemark = customerRemark == null ? null : customerRemark.trim();
    }
}