package com.pkh.pkec.phone.po;

import java.util.Date;

public class WorkOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.serial_no
     *
     * @mbggenerated
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.begintime
     *
     * @mbggenerated
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.endtime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.call_states
     *
     * @mbggenerated
     */
    private String callStates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.workorder_type
     *
     * @mbggenerated
     */
    private String workorderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.feedback
     *
     * @mbggenerated
     */
    private String feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.order_delete
     *
     * @mbggenerated
     */
    private String orderDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.handler
     *
     * @mbggenerated
     */
    private String handler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_workorder.sound_recording
     *
     * @mbggenerated
     */
    private String soundRecording;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.id
     *
     * @return the value of crm_workorder.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.id
     *
     * @param id the value for crm_workorder.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.serial_no
     *
     * @return the value of crm_workorder.serial_no
     *
     * @mbggenerated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.serial_no
     *
     * @param serialNo the value for crm_workorder.serial_no
     *
     * @mbggenerated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.customer_id
     *
     * @return the value of crm_workorder.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.customer_id
     *
     * @param customerId the value for crm_workorder.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.createtime
     *
     * @return the value of crm_workorder.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.createtime
     *
     * @param createtime the value for crm_workorder.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.begintime
     *
     * @return the value of crm_workorder.begintime
     *
     * @mbggenerated
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.begintime
     *
     * @param begintime the value for crm_workorder.begintime
     *
     * @mbggenerated
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.endtime
     *
     * @return the value of crm_workorder.endtime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.endtime
     *
     * @param endtime the value for crm_workorder.endtime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.updatetime
     *
     * @return the value of crm_workorder.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.updatetime
     *
     * @param updatetime the value for crm_workorder.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.channel
     *
     * @return the value of crm_workorder.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.channel
     *
     * @param channel the value for crm_workorder.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.call_states
     *
     * @return the value of crm_workorder.call_states
     *
     * @mbggenerated
     */
    public String getCallStates() {
        return callStates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.call_states
     *
     * @param callStates the value for crm_workorder.call_states
     *
     * @mbggenerated
     */
    public void setCallStates(String callStates) {
        this.callStates = callStates == null ? null : callStates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.workorder_type
     *
     * @return the value of crm_workorder.workorder_type
     *
     * @mbggenerated
     */
    public String getWorkorderType() {
        return workorderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.workorder_type
     *
     * @param workorderType the value for crm_workorder.workorder_type
     *
     * @mbggenerated
     */
    public void setWorkorderType(String workorderType) {
        this.workorderType = workorderType == null ? null : workorderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.feedback
     *
     * @return the value of crm_workorder.feedback
     *
     * @mbggenerated
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.feedback
     *
     * @param feedback the value for crm_workorder.feedback
     *
     * @mbggenerated
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.status
     *
     * @return the value of crm_workorder.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.status
     *
     * @param status the value for crm_workorder.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.order_delete
     *
     * @return the value of crm_workorder.order_delete
     *
     * @mbggenerated
     */
    public String getOrderDelete() {
        return orderDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.order_delete
     *
     * @param orderDelete the value for crm_workorder.order_delete
     *
     * @mbggenerated
     */
    public void setOrderDelete(String orderDelete) {
        this.orderDelete = orderDelete == null ? null : orderDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.handler
     *
     * @return the value of crm_workorder.handler
     *
     * @mbggenerated
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.handler
     *
     * @param handler the value for crm_workorder.handler
     *
     * @mbggenerated
     */
    public void setHandler(String handler) {
        this.handler = handler == null ? null : handler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_workorder.sound_recording
     *
     * @return the value of crm_workorder.sound_recording
     *
     * @mbggenerated
     */
    public String getSoundRecording() {
        return soundRecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_workorder.sound_recording
     *
     * @param soundRecording the value for crm_workorder.sound_recording
     *
     * @mbggenerated
     */
    public void setSoundRecording(String soundRecording) {
        this.soundRecording = soundRecording == null ? null : soundRecording.trim();
    }
}