package com.pkh.pkec.phone.mapper;

import com.pkh.pkec.phone.po.CrmOptionItem;
import com.pkh.pkec.phone.po.CrmOptionItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmOptionItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int countByExample(CrmOptionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int deleteByExample(CrmOptionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int insert(CrmOptionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int insertSelective(CrmOptionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    List<CrmOptionItem> selectByExample(CrmOptionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    CrmOptionItem selectByPrimaryKey(Integer optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CrmOptionItem record, @Param("example") CrmOptionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CrmOptionItem record, @Param("example") CrmOptionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CrmOptionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_option_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CrmOptionItem record);

    List<CrmOptionItem> selectAll();
}