package com.pkh.pkec.phone.mapper;

import com.pkh.pkec.phone.po.CustomerManage;
import com.pkh.pkec.phone.po.CustomerManageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int countByExample(CustomerManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int insert(CustomerManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int insertSelective(CustomerManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    List<CustomerManage> selectByExample(CustomerManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    CustomerManage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerManage record, @Param("example") CustomerManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerManage record, @Param("example") CustomerManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerManage record);
}