package com.pkh.pkec.phone.mapper;

import com.pkh.pkec.phone.po.WorkOrder;
import com.pkh.pkec.phone.po.WorkOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int countByExample(WorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int deleteByExample(WorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int insert(WorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int insertSelective(WorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    List<WorkOrder> selectByExample(WorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    WorkOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WorkOrder record, @Param("example") WorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WorkOrder record, @Param("example") WorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_workorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkOrder record);
}